setDefaults('as.Date.character', format = '%d/%M/%Y')
setwd("C:/Users/ravi.verma/Desktop/Coursera/Exploratory Data Analysis/Project1")
table <- read.table("household_power_consumption.txt", sep = ";", header = TRUE , colClasses = c(rep("factor",9)))
q <- subset(table, Date == "1/2/2007")
r <- subset(table, Date == "2/2/2007")
a <- rbind(q,r)
a$Global_active_power <- as.numeric(as.character(a$Global_active_power))
hist(a$Global_active_power, xlab = "Global Active Power (kilowatts)" , main = "Global Active Power",col ="red", ylim = c(0,1200))
dev.copy(png, file = "plot1.png")
dev.off()