library(Defaults)
setDefaults('as.Date.character', format = '%d/%M/%Y')
setwd("C:/Users/ravi.verma/Desktop/Coursera/Exploratory Data Analysis/Project1")
table <- read.table("household_power_consumption.txt", sep = ";", header = TRUE , colClasses = c(rep("factor",9)))
q <- subset(table, Date == "1/2/2007")
r <- subset(table, Date == "2/2/2007")
a <- rbind(q,r)
a$Global_active_power <- as.numeric(as.character(a$Global_active_power))
par(mar = c(3,4,2,1))
plot(1:nrow(a), a$Global_active_power,"l", xaxt = "n", ylab = "Global Active Power (Kilowatts)")
axis(1, at= c(1,nrow(a)/2,nrow(a)), labels = c("Thu","Fri","Sat"))
dev.copy(png, file = "plot2.png")
dev.off()