library(Defaults)
setDefaults('as.Date.character', format = '%d/%M/%Y')
setwd("C:/Users/ravi.verma/Desktop/Coursera/Exploratory Data Analysis/Project1")
table <- read.table("household_power_consumption.txt", sep = ";", header = TRUE , colClasses = c(rep("factor",9)))
q <- subset(table, Date == "1/2/2007")
r <- subset(table, Date == "2/2/2007")
a <- rbind(q,r)
a$Sub_metering_1 <- as.numeric(as.character(a$Sub_metering_1))
a$Sub_metering_2 <- as.numeric(as.character(a$Sub_metering_2))
a$Sub_metering_3 <- as.numeric(as.character(a$Sub_metering_3))
par(mar = c(3,4,2,1))
plot(1:nrow(a),a$Sub_metering_1,"l", xaxt = "n", ylab = "Energy Sub Metering")
lines(1:nrow(a),a$Sub_metering_2, col = "red")
lines(1:nrow(a),a$Sub_metering_3, col = "blue")
axis(1, at= c(1,nrow(a)/2,nrow(a)), labels = c("Thu","Fri","Sat"))
legend("topright", lty = c(1,1,1) , col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), text.font = 0.2)
dev.copy(png, file = "plot3.png")
dev.off()